server:
  port: ${PORT:8080}

spring:
  application:
    name: kookin-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect


