spring:
  datasource:
    url: "jdbc:h2:mem:kookin"
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect : org.hibernate.dialect.H2Dialect
