server:
  port: ${PORT:8080}

spring:
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  groupe-id: @project.groupId@
  application-name: @project.artifactId@
  version: @project.version@
